# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    camel_case_types: true
    camel_case_extensions: true
    annotate_overrides: true
    overridden_fields: true
    unnecessary_overrides: true
    avoid_implementing_value_types: true
    always_specify_types: true
    avoid_init_to_null: true
    prefer_const_constructors: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    always_declare_return_types: true
    await_only_futures: true
    file_names: true
