name: cgi_task_v1
description: "CGI TaskManager App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  uuid: ^4.4.2
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.0.3
  mockito: ^5.0.16
  build_runner: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/